# .streamlit/config.toml

# This file is used to configure your Streamlit app environment.

[server]

# Set the port the server listens on
port = 8501

[logger]

# The level of logging. Valid options are "info", "warning", "error", "debug".
level = "info"

[browser]

# Whether to open the browser automatically when the script is run.
gatherUsageStats = false
